hide_download: true
hide_download_original: null
leftnav:
- identifier: 08eadb06-a633-54c4-cd6b-05d2e80ec552
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 880ce463-534d-7eb8-d08f-0ce26c43d72e
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 7e84895c-4449-b574-f7db-fbd1a5a4d77b
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
